node {
  def frontendImage

  step([$class: 'WsCleanup'])
  
  stage("Checkout code"){
    checkout scm
  }

  try {
    stage("Run tests"){
      dir('frontend') {
        docker.image('node:10.11.0-alpine').inside {
          withEnv([
            /* Override the npm cache directory to avoid: EACCES: permission denied, mkdir '/.npm' */
            'npm_config_cache=npm-cache',
            /* Override HOME Path */
            'HOME=.'
          ]) {
            sh 'npm install'
            sh 'npm test'
          }
        }
      }
    }
  } catch (e) {

  } finally {
    junit '**/frontend/test-results.xml'
  }
  

  stage("Build artifact frontend image"){
    dir('frontend') {
      frontendImage = docker.build('david990612/frontend-icesi-health')
    }
  }

  stage("Pushing image to registry"){
    docker.withRegistry('', 'docker-hub') {
      frontendImage.push('$BUILD_NUMBER')
    }
  }

  stage("Clean environment - Removing unnecessary images"){
    sh 'docker image prune -a -f --filter "label!=david990612/frontend-icesi-health"'
  }


}