- hosts: tag_Name_tf_instance_front_icesi_health
  become: yes
  become_user: root
  become_method: sudo

      - name: Execute docker container
      docker_container:
        name: appDB
        image: apache/couthdb
        state: started
        pull: true
        published_ports:
          - "5984:5984"